<?php

/**
 * @file
 * Contains hook implementations for the Node Fields Complete Percentage module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function nfcp_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.entity_fields_complete_percentag':
      return t("Creates a percentage completed block display for selected node");
  }
}

/**
 * Implements hook_theme().
 */
function nfcp_theme($existing, $type, $theme, $path) {
  return [
    'nfcp_template' => [
      'variables' => [
        'nid' => NULL,
        'title' => NULL,
        'completed' => NULL,
        'incomplete' => NULL,
        'total' => NULL,
        'open_link' => NULL,
        'hide_nfcp_block' => NULL,
        'nextfield_name' => NULL,
        'nextfield_title' => NULL,
        'current_percent' => NULL,
        'next_percent' => NULL,
      ],
    ],
    'nfcp_admin_template' => [
      'variables' => [
        'nid' => NULL,
        'uid' => NULL,
        'title' => NULL,
        'completed' => NULL,
        'incomplete' => NULL,
        'total' => NULL,
        'open_link' => NULL,
        'hide_nfcp_block' => NULL,
        'nextfield_name' => NULL,
        'nextfield_title' => NULL,
        'current_percent' => NULL,
        'next_percent' => NULL,
      ],
    ],
  ];
}
